# Generated by Django 3.1.5 on 2021-02-12 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferAspectsMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Date when deleted', null=True, verbose_name='Deleted At')),
                ('delete_reason', models.CharField(blank=True, default=None, help_text='Delete Reason', max_length=300, null=True, verbose_name='Delete Reason')),
                ('name', models.CharField(help_text='Offer Aspect name', max_length=255, verbose_name='Offer Aspect name')),
                ('aspect_type', models.CharField(blank=True, choices=[('1', 'Closed'), ('2', 'Open')], help_text='Offer Aspect meta data type', max_length=128, null=True, verbose_name='Offer Aspect meta data type')),
                ('aspect_input_type', models.CharField(blank=True, choices=[('1', 'Single'), ('2', 'Multi')], help_text='Offer Aspect meta data input type', max_length=128, null=True, verbose_name='Offer Aspect meta data input type')),
            ],
            options={
                'verbose_name': 'Offer Aspects Meta Data',
                'verbose_name_plural': 'Offer Aspects Meta Data',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferAspectValuesMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Date when deleted', null=True, verbose_name='Deleted At')),
                ('delete_reason', models.CharField(blank=True, default=None, help_text='Delete Reason', max_length=300, null=True, verbose_name='Delete Reason')),
                ('value_name', models.CharField(help_text='Offer Value Name', max_length=255, verbose_name='Offer Value Name')),
                ('value_type', models.CharField(blank=True, choices=[('1', 'Text'), ('2', 'Number')], help_text='Offer Value type', max_length=128, null=True, verbose_name='Offer Value type')),
                ('aspect_meta_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_aspect_values_meta_data', to='offer.offeraspectsmetadata')),
            ],
            options={
                'verbose_name': 'Offer Aspect Values Meta Data',
                'verbose_name_plural': 'Offer Aspect Values Meta Data',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Date when deleted', null=True, verbose_name='Deleted At')),
                ('delete_reason', models.CharField(blank=True, default=None, help_text='Delete Reason', max_length=300, null=True, verbose_name='Delete Reason')),
                ('title', models.CharField(help_text='Offer title', max_length=255, verbose_name='Offer title')),
                ('seller_offer_id', models.CharField(help_text='Seller Offer Id', max_length=255, verbose_name='Seller Offer Id')),
                ('asin', models.CharField(help_text='ASIN', max_length=255, verbose_name='ASIN')),
                ('offer_url', models.TextField(blank=True, help_text='Offer URL', null=True, verbose_name='Offer URL')),
                ('offer_price', models.FloatField(blank=True, default=0, help_text='Offer Price', max_length=11, null=True, verbose_name='Offer Price')),
                ('offer_quantity', models.IntegerField(blank=True, default=0, help_text='Offer Quantity', null=True, verbose_name='Offer Quantity')),
                ('offer_reviews_count', models.IntegerField(blank=True, default=0, help_text='Offer Reviews Count', null=True, verbose_name='Offer Reviews Count')),
                ('offer_reviews_score', models.FloatField(blank=True, default=0, help_text='Offer Reviews Score', max_length=11, null=True, verbose_name='Offer Reviews Score')),
                ('offer_image_url', models.TextField(blank=True, help_text='Offer Image URL', null=True, verbose_name='Offer Image URL')),
                ('brand_name', models.CharField(help_text='Offer Brand Name', max_length=56, verbose_name='Offer Brand Name')),
                ('mpn', models.CharField(help_text='Manufacturur Part Number', max_length=56, verbose_name='Manufacturur Part Number')),
                ('offer_description', models.TextField(blank=True, help_text='Offer Description', null=True, verbose_name='Offer Description')),
                ('qualification_status', models.CharField(blank=True, choices=[('1', 'Qualified'), ('2', 'Rejected'), ('2', 'Pending')], help_text='Qualification Status', max_length=128, null=True, verbose_name='Qualification Status')),
                ('market_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_market_place', to='home.marketplace')),
                ('offer_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_language', to='home.language')),
                ('technical_aspect_values', models.ManyToManyField(related_name='offer_technical_aspect_values', to='offer.OfferAspectValuesMetaData')),
                ('technical_aspects', models.ManyToManyField(related_name='offer_technical_aspects', to='offer.OfferAspectsMetaData')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'ordering': ['-created_at'],
            },
        ),
    ]
